import { OAuth2Client } from 'google-auth-library';
const client = new OAuth2Client(process.env.GOOGLE_CLIENT_ID);

const verifyGoogleToken = async (token) => {
  try {
    // Check if the token is a JWT (ID Token) or an opaque string (Access Token)
    if (token.split('.').length === 3) {
      const ticket = await client.verifyIdToken({
        idToken: token,
        audience: process.env.GOOGLE_CLIENT_ID,
      });
      return ticket.getPayload();
    } else {
      // It's an Access Token (generated by useGoogleLogin hook)
      const response = await fetch('https://www.googleapis.com/oauth2/v3/userinfo', {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!response.ok) {
        throw new Error('Failed to fetch user info with access token');
      }
      return await response.json(); // Returns payload containing sub (as googleId), name, email.
    }
  } catch (error) {
    console.error('Error verifying Google Token', error);
    return null;
  }
};

export { verifyGoogleToken };
